import { useMemo, useRef, useState } from 'react'
import {
  AlignCenter, AlignLeft, AlignRight, BarChart3, Bold, CalendarDays, ChevronDown,
  Columns3, Database, Download, Eye, FileDown, FileSpreadsheet, FileText, GripVertical,
  Group, Image, Italic, LayoutTemplate, MoreHorizontal, PanelLeftClose, Plus, Redo2,
  Save, Search, Settings2, Table2, Type, Undo2, Upload, X
} from 'lucide-react'
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import * as XLSX from 'xlsx'
import { fields, initialColumns, rows } from './reportData'

const money = new Intl.NumberFormat('en-US', { style:'currency', currency:'USD', maximumFractionDigits:0 })
const niceDate = value => new Intl.DateTimeFormat('en-US', {month:'short', day:'2-digit', year:'numeric'}).format(new Date(value))
const downloadBlob = (content, type, filename) => {
  const link = document.createElement('a')
  link.href = URL.createObjectURL(new Blob([content], { type }))
  link.download = filename; link.click(); URL.revokeObjectURL(link.href)
}

function App() {
  const [columns, setColumns] = useState(initialColumns)
  const [selected, setSelected] = useState('amount')
  const [groupBy, setGroupBy] = useState('region')
  const [title, setTitle] = useState('Revenue by Customer')
  const [subtitle, setSubtitle] = useState('August 2026 · Sales performance overview')
  const [logo, setLogo] = useState(null)
  const [preview, setPreview] = useState(false)
  const [saved, setSaved] = useState(false)
  const [rightTab, setRightTab] = useState('format')
  const fileRef = useRef()

  const selectedCol = columns.find(c => c.id === selected)
  const groups = useMemo(() => {
    if (!groupBy) return [['All records', rows]]
    return Object.entries(rows.reduce((acc,row) => ((acc[row[groupBy]] ||= []).push(row), acc), {}))
  }, [groupBy])
  const total = rows.reduce((s,r) => s+r.amount, 0)

  const formatValue = (value, col) => {
    if (col.format === 'currency') return money.format(Number(value))
    if (col.format === 'date') return niceDate(value)
    if (col.format === 'number') return Number(value).toLocaleString()
    if (col.format === 'percent') return `${Number(value).toFixed(1)}%`
    return value
  }
  const patchColumn = patch => setColumns(cols => cols.map(c => c.id === selected ? {...c,...patch} : c))
  const addColumn = id => {
    if (columns.some(c => c.id === id)) return
    const field = fields.find(f => f.id === id)
    setColumns([...columns, { id, label:field.label, width:120, align:field.type === 'currency' || field.type === 'number'?'right':'left', format:field.type, color:'#24304a', bold:false }])
    setSelected(id)
  }
  const removeColumn = id => {
    const next = columns.filter(c => c.id !== id); setColumns(next)
    if (selected === id) setSelected(next[0]?.id)
  }
  const exportCsv = () => {
    const escape = v => `"${String(v ?? '').replaceAll('"','""')}"`
    const lines = [columns.map(c=>escape(c.label)).join(','), ...rows.map(r=>columns.map(c=>escape(formatValue(r[c.id],c))).join(','))]
    downloadBlob(lines.join('\n'), 'text/csv;charset=utf-8', 'revenue-report.csv')
  }
  const exportExcel = () => {
    const data = rows.map(r => Object.fromEntries(columns.map(c => [c.label, r[c.id]])))
    const ws = XLSX.utils.json_to_sheet(data); ws['!cols'] = columns.map(c => ({wch:Math.max(12, c.width/8)}))
    const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, 'Revenue Report')
    XLSX.writeFile(wb, 'revenue-report.xlsx')
  }
  const exportPdf = () => {
    const doc = new jsPDF({orientation:'portrait', unit:'pt', format:'a4'})
    doc.setFillColor(29,42,68); doc.rect(0,0,595,76,'F'); doc.setTextColor(255); doc.setFontSize(19); doc.text(title, 36, 36)
    doc.setFontSize(9); doc.setTextColor(205,214,230); doc.text(subtitle,36,54)
    autoTable(doc,{ startY:102, head:[columns.map(c=>c.label)], body:rows.map(r=>columns.map(c=>formatValue(r[c.id],c))), theme:'grid', headStyles:{fillColor:[38,72,116]}, styles:{fontSize:8,cellPadding:5}, margin:{left:30,right:30} })
    doc.setFontSize(8); doc.setTextColor(110); doc.text('Generated by Paginated Report Studio',36,810); doc.save('revenue-report.pdf')
  }
  const onImage = e => {
    const file = e.target.files?.[0]; if (!file) return
    const reader = new FileReader(); reader.onload = ev => setLogo(ev.target.result); reader.readAsDataURL(file)
  }

  return <div className={`app ${preview?'preview-mode':''}`}>
    <header className="topbar">
      <div className="brand"><div className="brand-mark"><BarChart3 size={19}/></div><div><strong>Report Studio</strong><span>Paginated designer</span></div></div>
      <div className="report-name"><span>Sales workspace</span><b>/</b><input value={title} onChange={e=>setTitle(e.target.value)}/><ChevronDown size={14}/></div>
      <div className="top-actions">
        <button className="icon-btn" title="Undo"><Undo2 size={17}/></button><button className="icon-btn" title="Redo"><Redo2 size={17}/></button>
        <i></i><button className="btn ghost" onClick={()=>setPreview(!preview)}><Eye size={16}/>{preview?'Edit':'Preview'}</button>
        <button className="btn ghost" onClick={()=>{localStorage.setItem('paginated-report',JSON.stringify({title,subtitle,columns,groupBy}));setSaved(true);setTimeout(()=>setSaved(false),1600)}}><Save size={16}/>{saved?'Saved!':'Save'}</button>
        <div className="export-wrap"><button className="btn primary"><Download size={16}/> Export <ChevronDown size={14}/></button><div className="export-menu"><button onClick={exportPdf}><FileText/>PDF document</button><button onClick={exportExcel}><FileSpreadsheet/>Excel workbook</button><button onClick={exportCsv}><FileDown/>CSV data</button></div></div>
        <button className="avatar">AR</button>
      </div>
    </header>

    <div className="workspace">
      <aside className="left-panel">
        <div className="panel-head"><div><Database size={16}/><strong>Data</strong></div><button className="icon-btn"><MoreHorizontal size={17}/></button></div>
        <div className="dataset"><span className="db-icon"><Database size={15}/></span><div><strong>Sales overview</strong><small>Sample dataset · 8 fields</small></div><ChevronDown size={14}/></div>
        <div className="search"><Search size={15}/><input placeholder="Search fields..."/></div>
        <div className="section-label">FIELDS <Plus size={14}/></div>
        <div className="field-list">{fields.map(field => <button key={field.id} draggable onDragStart={e=>e.dataTransfer.setData('field',field.id)} onDoubleClick={()=>addColumn(field.id)} className={columns.some(c=>c.id===field.id)?'used':''}>
          <GripVertical size={14}/><span className={`type-icon ${field.type}`}>{field.type==='date'?<CalendarDays/>:field.type==='currency'?'$':field.type==='number'?'#':'Ab'}</span><span>{field.label}</span>{columns.some(c=>c.id===field.id)&&<span className="dot"/>}
        </button>)}</div>
        <div className="section-label">REPORT STRUCTURE</div>
        <div className="structure"><button><LayoutTemplate/>Page header</button><button><Group/>Group: {groupBy||'None'}</button><button className="active"><Table2/>Detail table <span>{columns.length}</span></button><button><LayoutTemplate/>Page footer</button></div>
      </aside>

      <main className="canvas-wrap" onDragOver={e=>e.preventDefault()} onDrop={e=>addColumn(e.dataTransfer.getData('field'))}>
        {!preview && <div className="canvas-toolbar"><div><button className="active">Design</button><button onClick={()=>setPreview(true)}>Print preview</button></div><span>100%</span><div className="zoom"><button>−</button><span>100%</span><button>+</button></div></div>}
        <div className="page-label">PAGE 1 OF 1 · LETTER PORTRAIT</div>
        <article className="page">
          <section className="page-header">
            <div className="report-heading">{logo?<img src={logo}/>:<div className="logo-placeholder">N</div>}<div><input value={title} onChange={e=>setTitle(e.target.value)}/><input value={subtitle} onChange={e=>setSubtitle(e.target.value)}/></div></div>
            <div className="period"><span>REPORT PERIOD</span><strong>Aug 01 – Aug 31, 2026</strong></div>
          </section>
          <section className="summary-strip"><div><span>Total revenue</span><strong>{money.format(total)}</strong></div><div><span>Invoices</span><strong>{rows.length}</strong></div><div><span>Average order</span><strong>{money.format(total/rows.length)}</strong></div><div><span>Paid rate</span><strong>{Math.round(rows.filter(r=>r.status==='Paid').length/rows.length*100)}%</strong></div></section>
          <section className="report-body">
            {groups.map(([name, data]) => <div className="report-group" key={name}>
              {groupBy && <div className="group-heading"><span>{fields.find(f=>f.id===groupBy)?.label}</span><strong>{name}</strong><em>{data.length} records</em><b>{money.format(data.reduce((s,r)=>s+r.amount,0))}</b></div>}
              <table><thead><tr>{columns.map(col=><th key={col.id} className={selected===col.id?'selected':''} style={{width:col.width,textAlign:col.align}} onClick={()=>setSelected(col.id)}>{col.label}{!preview&&<button onClick={e=>{e.stopPropagation();removeColumn(col.id)}}><X/></button>}</th>)}</tr></thead>
              <tbody>{data.map(row=><tr key={row.invoice}>{columns.map(col=><td key={col.id} onClick={()=>setSelected(col.id)} className={selected===col.id?'selected':''} style={{textAlign:col.align,color:col.color,fontWeight:col.bold?700:400,fontStyle:col.italic?'italic':'normal'}}>{col.id==='status'?<span className={`status ${row.status.toLowerCase()}`}>{row.status}</span>:formatValue(row[col.id],col)}</td>)}</tr>)}</tbody>
              </table>
            </div>)}
            <div className="grand-total"><span>GRAND TOTAL</span><strong>{money.format(total)}</strong></div>
          </section>
          <footer className="page-footer"><span>CONFIDENTIAL · INTERNAL USE ONLY</span><span>Generated Aug 18, 2026</span><span>Page 1 of 1</span></footer>
        </article>
      </main>

      <aside className="right-panel">
        <div className="property-tabs"><button className={rightTab==='format'?'active':''} onClick={()=>setRightTab('format')}><Settings2/>Format</button><button className={rightTab==='layout'?'active':''} onClick={()=>setRightTab('layout')}><Columns3/>Layout</button></div>
        {selectedCol ? <div className="properties">
          <div className="selection-title"><span>SELECTED ELEMENT</span><strong><Columns3/>Column · {selectedCol.label}</strong></div>
          <Property title="Field">
            <label>Label<input value={selectedCol.label} onChange={e=>patchColumn({label:e.target.value})}/></label>
            <label>Data format<select value={selectedCol.format} onChange={e=>patchColumn({format:e.target.value})}><option>text</option><option>number</option><option>currency</option><option>percent</option><option>date</option></select></label>
          </Property>
          <Property title="Typography">
            <label>Text color<div className="color-input"><input type="color" value={selectedCol.color} onChange={e=>patchColumn({color:e.target.value})}/><input value={selectedCol.color} onChange={e=>patchColumn({color:e.target.value})}/></div></label>
            <div className="format-buttons"><button className={selectedCol.bold?'active':''} onClick={()=>patchColumn({bold:!selectedCol.bold})}><Bold/></button><button className={selectedCol.italic?'active':''} onClick={()=>patchColumn({italic:!selectedCol.italic})}><Italic/></button><i/><button className={selectedCol.align==='left'?'active':''} onClick={()=>patchColumn({align:'left'})}><AlignLeft/></button><button className={selectedCol.align==='center'?'active':''} onClick={()=>patchColumn({align:'center'})}><AlignCenter/></button><button className={selectedCol.align==='right'?'active':''} onClick={()=>patchColumn({align:'right'})}><AlignRight/></button></div>
          </Property>
          <Property title="Size & position"><label>Column width<div className="range-row"><input type="range" min="70" max="260" value={selectedCol.width} onChange={e=>patchColumn({width:+e.target.value})}/><span>{selectedCol.width}px</span></div></label></Property>
          <Property title="Grouping"><label>Group report by<select value={groupBy} onChange={e=>setGroupBy(e.target.value)}><option value="">No grouping</option>{fields.filter(f=>f.type==='text').map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></label></Property>
          <Property title="Media"><button className="upload-btn" onClick={()=>fileRef.current.click()}><Upload/>Upload report logo</button><input ref={fileRef} hidden type="file" accept="image/*" onChange={onImage}/>{logo&&<button className="remove-image" onClick={()=>setLogo(null)}>Remove image</button>}</Property>
        </div>:<div className="empty-selection"><PanelLeftClose/><strong>Select a column</strong><span>Choose an element on the canvas to format it.</span></div>}
      </aside>
    </div>
  </div>
}

function Property({title,children}) {
  return <section className="property"><h3>{title}<ChevronDown size={14}/></h3><div>{children}</div></section>
}

export default App
